In [10]:
import sys
sys.path.append('../')
sys.path.append('../../')

from errorpro.interactive import *
init(locals())


In [76]:
import numpy as np
a = np.arange(24).reshape(2,3,4)
print(a)
for x in np.nditer([a], op_flags=["readonly","allocate"], op_axes=[[1,2]], itershape=(3,4)):
    print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
0
1
2
3
4
5
6
7
8
9
10
11


In [6]:
from scipy.optimize import curve_fit
from numpy import float_
def func(x, m, b):
    return m*x+b
xdata = (float_([[1,2,3],[1,2,3]])).flatten()
ydata = (float_([[2,3,4.1],[2,3,4.1]])).flatten()
params_opt, params_covar = curve_fit(func, xdata, ydata)
print(params_opt)
print(np.sqrt(np.diag(params_covar)))

[ 1.05        0.93333333]
[ 0.01443376  0.03118048]


In [2]:
%%eq
z = 2 <0.1> [m]
a = z**2

In [3]:
z = assign(2,0.1,name="z")
a = assign(sin(z**2),name="a")
a

a

In [4]:
%%eq
{
t [s], E [J]
    1 6.3
    2 7.4
    3 7.9
    4 8.7
    5 9.5
    6 10.3
}

In [23]:
fit(m*t + b, t, E, [m,b], weighted=False)

<IPython.core.display.Latex object>