In [ ]:
import sys
sys.path.append('../')
sys.path.append('../../')

from errorpro.interactive import *
init(locals())


In [ ]:
from scipy.optimize import curve_fit
from numpy import float_
def func(x, m, b):
    return m*x+b
xdata = (float_([[1,2,3],[1,2,3]])).flatten()
ydata = (float_([[2,3,4.1],[2,3,4.1]])).flatten()
params_opt, params_covar = curve_fit(func, xdata, ydata)
print(params_opt)
print(np.sqrt(np.diag(params_covar)))

In [ ]:
%%eq
z = 2 <0.1> [m]
a = z**2

In [ ]:
z = assign(2,0.1,name="z")
a = assign(sin(z**2),name="a")
a

In [1]:
import sys
sys.path.append('../')
sys.path.append('../../')

from errorpro.interactive import *
init(locals())


In [2]:
%%eq
{
t [s], E [J]
    1 6.3
    2 7.4
    3 7.9
    4 8.7
    5 9.5
    6 10.3
}

In [7]:
a = [1,3,4,5,6,7]
b = [2.1,0,-0.1,-0.2,-0.3,-0.5]
c = [3,-3,5,6,7,8]
short = assign([3,4,5])
E = assign([a,b,c],[0.2,3,4,1,0.5,2],name="E")
F = assign([a,b,c],name="F")
#np.float_([[2,3,4,5,6],[34,4,5,6,7,4]])
E.value

array([[ 1. ,  3. ,  4. ,  5. ,  6. ,  7. ],
       [ 2.1,  0. , -0.1, -0.2, -0.3, -0.5],
       [ 3. , -3. ,  5. ,  6. ,  7. ,  8. ]])

In [8]:

m,b = params("m b")
fit(m*t + b, t, E, [m,b], ydata_axes=1)

(array([ 1.        , -1.96666667]), array([[ 0.00333333, -0.01333333],
       [-0.01333333,  0.05555555]]))
(array([ -3.,  12.]), array([[ 0., -0.],
       [-0.,  0.]]))
(array([ 0.5       ,  0.96666667]), array([[   7.05333333,  -28.21333328],
       [ -28.21333328,  117.55555507]]))
(array([ 0.5,  1.6]), array([[  10.83      ,  -43.3200007 ],
       [ -43.3200007 ,  180.50000583]]))
(array([ 0.5       ,  2.23333333]), array([[  15.41333333,  -61.65333399],
       [ -61.65333399,  256.88889438]]))
(array([ 0.5       ,  2.83333333]), array([[  21.33333333,  -85.33333333],
       [ -85.33333333,  355.55555556]]))


<IPython.core.display.Latex object>